### ISSUE TITLE
Pharlap not starting

### ISSUE THREAD

**Issue by Temujin0** [kororaproject/kp-pharlap#20]
I'm running k23 fully updated fresh install mate DE
`pharlap-cli debug 
Traceback (most recent call last):
  File "/usr/bin/pharlap-cli", line 22, in <module>
    import Pharlap.detect
  File "/usr/lib/python3.4/site-packages/Pharlap/detect.py", line 26, in <module>
    system_architecture = dnf.arch.basearch( hawkey.detect_arch() )
AttributeError: 'module' object has no attribute 'arch'
`

Need anything elase let me know

**Comment by csmart** [comment]
This should be fixed by commit e7652a6a25cdf07a8366b328eed07723cb482ae8 and new packages will land soon.

**Comment by csmart** [comment]
You can test this with:
```bash
sudo dnf --enablerepo=korora-testing upgrade pharlap
```

**Comment by Temujin0** [comment]
I'll give it a try first thing tomorrow. Thanks for pointing me to the right place.

**Comment by Temujin0** [comment]
tested and works as it should thanks

**Comment by csmart** [comment]
great, pushed to stable repo, thanks!
