### ISSUE TITLE
Pharlap not Recognising Hardware

### ISSUE THREAD

**Issue by jimkp** [kororaproject/kp-pharlap#6]
see https://kororaproject.org/support/engage/problem/k21-darla-beta-pharlap-problem

Nvidia GTx770 not recognised in 21 beta

**Comment by csmart** [comment]
According to nvidia.com the latest stable driver for your card is driver version 340.65, although it does also list the beta versions of 343 and 346. If I look up the 343 driver, your card is listed as supported, so I'm not sure why pharlap didn't pick it up. Might need @firnsy to look into this one - is there a way to get pharlap to dump a list of the detected PCI ids or something (maybe like that debug mode we talked about)?

**Comment by csmart** [comment]
OK, I think this was solved with the bug fixes firnsy did yesterday. I'll add a message on that engage post.

**Comment by jimkp** [comment]
Closing as fixed by update
