### ISSUE TITLE
pharlap-cli devices crash

### ISSUE THREAD

**Issue by csmart** [kororaproject/kp-pharlap#8]
In case this is causing problems elsewhere..

``` bash
[08:52] chris@x220 ~ $ pharlap-cli devices
Checking alias pci:v00008086d00000126sv000017AAsd000021DAbc03sc00i00 (4%) ...
Checking alias pci:v00008086d00001C20sv000017AAsd000021DAbc04sc03i00 (13%) ...
Checking alias pci:v00008086d00001502sv000017AAsd000021CEbc02sc00i00 (22%) ...
Checking alias pci:v00001033d00000194sv000017AAsd000021DAbc0Csc03i30 (31%) ...
Checking alias pci:v00008086d00000085sv00008086sd00001311bc02sc80i00 (40%) ...
Checking alias pci:v00008086d00001C03sv000017AAsd000021DAbc01sc06i01 (50%) ...
Checking alias pci:v00008086d00001C3Asv000017AAsd000021DAbc07sc80i00 (59%) ...
Checking alias pci:v00008086d00001C22sv000017AAsd000021DAbc0Csc05i00 (68%) ...
Checking alias pci:v00001180d0000E823sv000017AAsd000021DAbc08sc80i01 (77%) ...
Checking alias pci:v00008086d00001C4Fsv000017AAsd000021DAbc06sc01i00 (86%) ...
Checking alias pci:v00008086d00000104sv000017AAsd000021DAbc06sc00i00 (95%) ...
Traceback (most recent call last):
  File "/usr/bin/pharlap-cli", line 177, in <module>
    sys.exit(command(args))
  File "/usr/bin/pharlap-cli", line 57, in command_devices
    drivers = Pharlap.detect.system_device_drivers()
  File "/usr/lib/python3.4/site-packages/Pharlap/detect.py", line 593, in system_device_drivers
    device_name = pkginfo['plugin']
```

KeyError: 'plugin'

**Comment by Aikidouke** [comment]
I get this error two. Installed k20 mate in vm - fedup -> k21 and run pharlap from gui fails. Running pharlap via sudo /usr/bin/pharlap gives;

Loading fallback: qt
Loading fallback: qt5
Traceback (most recent call last):
  File "/usr/bin/pharlap", line 122, in <module>
    app = App(name="Pharlap", width=792, height=496, inspector=True)
  File "/usr/lib/python3.4/site-packages/lens/app.py", line 96, in __init__
    toolkit_klass = App.__get_toolkit(toolkit.lower())
  File "/usr/lib/python3.4/site-packages/lens/app.py", line 65, in __get_toolkit
    raise Exception('No fallback toolkits implemented or loaded.')
Exception: No fallback toolkits implemented or loaded.

**Comment by csmart** [comment]
@Aikidouke are you on KDE? If so, please install this and try again:

```bash
sudo yum install -y python3-PyQt4
```

**Comment by Aikidouke** [comment]
No, I am running Mate. I had a Mate install of K20 in a VM that I ran fedup
on.

On Tue, Jan 13, 2015 at 6:15 PM, Christopher Smart <notifications@github.com

**Comment by csmart** [comment]
OK, can you please try installing this:

```bash
sudo yum -y install webkitgtk4
```

**Comment by Aikidouke** [comment]
Christopher,

That did the trick, pharlap runs with no error now.

Thanks,
Zach

On Wed, Jan 14, 2015 at 2:16 AM, Christopher Smart <notifications@github.com
